[package]
name = "smm-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
users = "0.11"
anyhow = "1.0"

[[bin]]
name = "smm-helper"
path = "src/main.rs"
